#!/usr/bin/env bash
set -euo pipefail

# ReqRadar one-click deployment script (Linux / macOS)
# Automates: env check, frontend build, backend install, config init, DB migration, server start
#
# Usage:
#   ./scripts/deploy.sh                  # Full deploy
#   ./scripts/deploy.sh --skip-frontend # Skip frontend build
#   ./scripts/deploy.sh --dev           # Development mode with --reload
#   ./scripts/deploy.sh --port 9000     # Custom port

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

SKIP_FRONTEND=false
SKIP_MIGRATE=false
SKIP_CONFIG=false
DEV_MODE=false
CUSTOM_PORT=""
CUSTOM_HOST=""

for arg in "$@"; do
    case "$arg" in
        --skip-frontend) SKIP_FRONTEND=true ;;
        --skip-migrate) SKIP_MIGRATE=true ;;
        --skip-config) SKIP_CONFIG=true ;;
        --dev) DEV_MODE=true ;;
        --port=*) CUSTOM_PORT="${arg#--port=}" ;;
        --host=*) CUSTOM_HOST="${arg#--host=}" ;;
        --help|-h)
            echo "Usage: $0 [--skip-frontend] [--skip-migrate] [--skip-config] [--dev] [--port PORT] [--host HOST]"
            exit 0
            ;;
    esac
done

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

step()   { echo -e "\n${CYAN}==> $1${NC}"; }
ok()     { echo -e "    ${GREEN}OK: $1${NC}"; }
warn()   { echo -e "    ${YELLOW}WARNING: $1${NC}"; }
err()    { echo -e "    ${RED}ERROR: $1${NC}"; }

# ── 1. Environment checks ──

step "Checking environment..."

if command -v python3 &>/dev/null; then
    PY_CMD="python3"
elif command -v python &>/dev/null; then
    PY_CMD="python"
else
    err "Python 3.12+ is required."
    exit 1
fi

PY_VER=$($PY_CMD --version 2>&1)
ok "Python: $PY_VER"

if ! command -v poetry &>/dev/null; then
    err "Poetry is not installed. Install from https://python-poetry.org"
    err "Run: pip install poetry  or  curl -sSL https://install.python-poetry.org | python3 -"
    exit 1
fi
ok "Poetry: $(poetry --version 2>&1 | head -1)"

if [ "$SKIP_FRONTEND" = false ]; then
    if command -v node &>/dev/null; then
        ok "Node.js: $(node --version)"
    else
        warn "Node.js not found. Frontend build will be skipped."
        warn "Install Node.js 18+ from https://nodejs.org or use --skip-frontend"
        SKIP_FRONTEND=true
    fi
fi

# ── 2. Frontend build ──

if [ "$SKIP_FRONTEND" = false ]; then
    step "Building frontend..."
    cd "$PROJECT_ROOT/frontend"
    npm ci --prefer-offline
    npm run build

    if [ -f "$PROJECT_ROOT/src/reqradar/web/static/index.html" ]; then
        ok "Frontend build succeeded"
    else
        err "Frontend build failed - index.html not found"
        exit 1
    fi
else
    step "Skipping frontend build"
fi

# ── 3. Backend dependencies ──

step "Installing Python dependencies..."
cd "$PROJECT_ROOT"
poetry install --no-interaction
ok "Dependencies installed"

# ── 4. Configuration ──

if [ "$SKIP_CONFIG" = false ]; then
    step "Checking configuration..."

    YML_FILE="$PROJECT_ROOT/.reqradar.yaml"
    EXAMPLE_YML="$PROJECT_ROOT/.reqradar.yaml.example"
    ENV_FILE="$PROJECT_ROOT/.env"

    if [ ! -f "$YML_FILE" ] && [ -f "$EXAMPLE_YML" ]; then
        cp "$EXAMPLE_YML" "$YML_FILE"
        ok "Created .reqradar.yaml from example"
    elif [ -f "$YML_FILE" ]; then
        ok ".reqradar.yaml already exists"
    else
        warn "No .reqradar.yaml found. Defaults will be used."
    fi

    if [ ! -f "$ENV_FILE" ]; then
        NEED_KEY=true
        API_KEY=""
        SECRET_KEY=""

        if [ -f "$YML_FILE" ]; then
            if grep -qP 'api_key:\s+\S+' "$YML_FILE" && ! grep -qP 'api_key:\s+\$\{' "$YML_FILE"; then
                NEED_KEY=false
            fi
        fi

        if [ "$NEED_KEY" = true ]; then
            echo ""
            echo -e "${YELLOW}ReqRadar requires an LLM API key to function.${NC}"
            if [ -t 0 ]; then
                read -rp "    Enter OPENAI_API_KEY (or compatible API key): " API_KEY
            else
                warn "No interactive terminal - set OPENAI_API_KEY environment variable manually"
            fi
            SECRET_KEY=$(openssl rand -hex 16 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(16))" 2>/dev/null || echo "change-me-in-production")
        fi

        if [ -n "$API_KEY" ] || [ -n "$SECRET_KEY" ]; then
            {
                echo "# ReqRadar Environment Configuration"
                echo "# Generated by deploy script - edit as needed"
                echo ""
                [ -n "$API_KEY" ] && echo "OPENAI_API_KEY=$API_KEY"
                [ -n "$SECRET_KEY" ] && echo "REQRADAR_SECRET_KEY=$SECRET_KEY"
            } > "$ENV_FILE"
            ok "Created .env with API key and secret key"
        fi
    else
        ok ".env already exists"
    fi
else
    step "Skipping configuration"
fi

# ── 5. Database migration ──

if [ "$SKIP_MIGRATE" = false ]; then
    step "Running database migrations..."
    cd "$PROJECT_ROOT"
    poetry run alembic upgrade head || {
        warn "Migration failed. Tables will be auto-created if needed."
    }
    ok "Database migrations applied"
else
    step "Skipping database migrations"
fi

# ── 6. Start server ──

step "Starting ReqRadar server..."

SERVE_ARGS=""
[ -n "$CUSTOM_PORT" ] && SERVE_ARGS="$SERVE_ARGS --port $CUSTOM_PORT"
[ -n "$CUSTOM_HOST" ] && SERVE_ARGS="$SERVE_ARGS --host $CUSTOM_HOST"
[ "$DEV_MODE" = true ] && SERVE_ARGS="$SERVE_ARGS --reload"

DISPLAY_PORT="${CUSTOM_PORT:-8000}"

echo ""
echo -e "${GREEN}ReqRadar is ready!${NC}"
echo -e "    Web UI: http://localhost:${DISPLAY_PORT}/app/"
echo -e "    API:    http://localhost:${DISPLAY_PORT}/health"
echo ""

cd "$PROJECT_ROOT"
exec poetry run reqradar serve $SERVE_ARGS